#!/usr/bin/env ruby
#^syntax detection

# Use 'librarian-chef install' to install new cookbooks from Opscode.

site 'http://community.opscode.com/api/v1'

cookbook 'dmg'
cookbook 'homebrew'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
